
package introsde.document.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DB", targetNamespace = "http://soap.document.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DB {


    /**
     * 
     * @param idFood
     * @return
     *     returns introsde.document.soap.Food
     */
    @WebMethod
    @WebResult(name = "food", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "getFoodById", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetFoodById")
    @ResponseWrapper(localName = "getFoodByIdResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetFoodByIdResponse")
    @Action(input = "http://soap.document.introsde/DB/getFoodByIdRequest", output = "http://soap.document.introsde/DB/getFoodByIdResponse")
    public Food getFoodById(
        @WebParam(name = "idFood", targetNamespace = "")
        Long idFood);

    /**
     * 
     * @param type
     * @return
     *     returns java.util.List<introsde.document.soap.Food>
     */
    @WebMethod
    @WebResult(name = "foods", targetNamespace = "")
    @RequestWrapper(localName = "getFoodByType", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetFoodByType")
    @ResponseWrapper(localName = "getFoodByTypeResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetFoodByTypeResponse")
    @Action(input = "http://soap.document.introsde/DB/getFoodByTypeRequest", output = "http://soap.document.introsde/DB/getFoodByTypeResponse")
    public List<Food> getFoodByType(
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.document.soap.Food>
     */
    @WebMethod
    @WebResult(name = "foods", targetNamespace = "")
    @RequestWrapper(localName = "getAllFood", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetAllFood")
    @ResponseWrapper(localName = "getAllFoodResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetAllFoodResponse")
    @Action(input = "http://soap.document.introsde/DB/getAllFoodRequest", output = "http://soap.document.introsde/DB/getAllFoodResponse")
    public List<Food> getAllFood();

    /**
     * 
     * @param calories
     * @return
     *     returns java.util.List<introsde.document.soap.Food>
     */
    @WebMethod
    @WebResult(name = "foods", targetNamespace = "")
    @RequestWrapper(localName = "getFoodByCaloriesBound", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetFoodByCaloriesBound")
    @ResponseWrapper(localName = "getFoodByCaloriesBoundResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetFoodByCaloriesBoundResponse")
    @Action(input = "http://soap.document.introsde/DB/getFoodByCaloriesBoundRequest", output = "http://soap.document.introsde/DB/getFoodByCaloriesBoundResponse")
    public List<Food> getFoodByCaloriesBound(
        @WebParam(name = "calories", targetNamespace = "")
        double calories);

    /**
     * 
     * @param foodIn
     * @return
     *     returns introsde.document.soap.Food
     */
    @WebMethod
    @WebResult(name = "food", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "createFood", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.CreateFood")
    @ResponseWrapper(localName = "createFoodResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.CreateFoodResponse")
    @Action(input = "http://soap.document.introsde/DB/createFoodRequest", output = "http://soap.document.introsde/DB/createFoodResponse")
    public Food createFood(
        @WebParam(name = "foodIn", targetNamespace = "")
        Food foodIn);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.document.soap.User>
     */
    @WebMethod
    @WebResult(name = "users", targetNamespace = "")
    @RequestWrapper(localName = "getAllUser", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetAllUser")
    @ResponseWrapper(localName = "getAllUserResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetAllUserResponse")
    @Action(input = "http://soap.document.introsde/DB/getAllUserRequest", output = "http://soap.document.introsde/DB/getAllUserResponse")
    public List<User> getAllUser();

    /**
     * 
     * @param idUser
     * @return
     *     returns introsde.document.soap.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetUserByIdResponse")
    @Action(input = "http://soap.document.introsde/DB/getUserByIdRequest", output = "http://soap.document.introsde/DB/getUserByIdResponse")
    public User getUserById(
        @WebParam(name = "idUser", targetNamespace = "")
        Long idUser);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns introsde.document.soap.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "getUserByUsernamePassword", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetUserByUsernamePassword")
    @ResponseWrapper(localName = "getUserByUsernamePasswordResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetUserByUsernamePasswordResponse")
    @Action(input = "http://soap.document.introsde/DB/getUserByUsernamePasswordRequest", output = "http://soap.document.introsde/DB/getUserByUsernamePasswordResponse")
    public User getUserByUsernamePassword(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param userIn
     * @return
     *     returns introsde.document.soap.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "createUser", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.CreateUserResponse")
    @Action(input = "http://soap.document.introsde/DB/createUserRequest", output = "http://soap.document.introsde/DB/createUserResponse")
    public User createUser(
        @WebParam(name = "userIn", targetNamespace = "")
        User userIn);

    /**
     * 
     * @param userIn
     * @return
     *     returns introsde.document.soap.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.UpdateUserResponse")
    @Action(input = "http://soap.document.introsde/DB/updateUserRequest", output = "http://soap.document.introsde/DB/updateUserResponse")
    public User updateUser(
        @WebParam(name = "userIn", targetNamespace = "")
        User userIn);

    /**
     * 
     * @param userIn
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeUser", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.RemoveUser")
    @ResponseWrapper(localName = "removeUserResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.RemoveUserResponse")
    @Action(input = "http://soap.document.introsde/DB/removeUserRequest", output = "http://soap.document.introsde/DB/removeUserResponse")
    public boolean removeUser(
        @WebParam(name = "userIn", targetNamespace = "")
        User userIn);

    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns introsde.document.soap.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "loginUser", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.LoginUser")
    @ResponseWrapper(localName = "loginUserResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.LoginUserResponse")
    @Action(input = "http://soap.document.introsde/DB/loginUserRequest", output = "http://soap.document.introsde/DB/loginUserResponse")
    public User loginUser(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param idUser
     * @param secondPassword
     * @param firstPassword
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePassword", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.UpdatePassword")
    @ResponseWrapper(localName = "updatePasswordResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.UpdatePasswordResponse")
    @Action(input = "http://soap.document.introsde/DB/updatePasswordRequest", output = "http://soap.document.introsde/DB/updatePasswordResponse")
    public boolean updatePassword(
        @WebParam(name = "idUser", targetNamespace = "")
        long idUser,
        @WebParam(name = "firstPassword", targetNamespace = "")
        String firstPassword,
        @WebParam(name = "secondPassword", targetNamespace = "")
        String secondPassword);

    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "controlUsernamePassword", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.ControlUsernamePassword")
    @ResponseWrapper(localName = "controlUsernamePasswordResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.ControlUsernamePasswordResponse")
    @Action(input = "http://soap.document.introsde/DB/controlUsernamePasswordRequest", output = "http://soap.document.introsde/DB/controlUsernamePasswordResponse")
    public boolean controlUsernamePassword(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.document.soap.Activity>
     */
    @WebMethod
    @WebResult(name = "activities", targetNamespace = "")
    @RequestWrapper(localName = "getAllActivity", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetAllActivity")
    @ResponseWrapper(localName = "getAllActivityResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetAllActivityResponse")
    @Action(input = "http://soap.document.introsde/DB/getAllActivityRequest", output = "http://soap.document.introsde/DB/getAllActivityResponse")
    public List<Activity> getAllActivity();

    /**
     * 
     * @param idUser
     * @return
     *     returns java.util.List<introsde.document.soap.Activity>
     */
    @WebMethod
    @WebResult(name = "activities", targetNamespace = "")
    @RequestWrapper(localName = "getActivityByIdUser", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetActivityByIdUser")
    @ResponseWrapper(localName = "getActivityByIdUserResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetActivityByIdUserResponse")
    @Action(input = "http://soap.document.introsde/DB/getActivityByIdUserRequest", output = "http://soap.document.introsde/DB/getActivityByIdUserResponse")
    public List<Activity> getActivityByIdUser(
        @WebParam(name = "idUser", targetNamespace = "")
        Long idUser);

    /**
     * 
     * @param idActivity
     * @return
     *     returns introsde.document.soap.Activity
     */
    @WebMethod
    @WebResult(name = "activity", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "getActivityById", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetActivityById")
    @ResponseWrapper(localName = "getActivityByIdResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetActivityByIdResponse")
    @Action(input = "http://soap.document.introsde/DB/getActivityByIdRequest", output = "http://soap.document.introsde/DB/getActivityByIdResponse")
    public Activity getActivityById(
        @WebParam(name = "idActivity", targetNamespace = "")
        Long idActivity);

    /**
     * 
     * @param type
     * @return
     *     returns java.util.List<introsde.document.soap.Activity>
     */
    @WebMethod
    @WebResult(name = "activities", targetNamespace = "")
    @RequestWrapper(localName = "getActivityByType", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetActivityByType")
    @ResponseWrapper(localName = "getActivityByTypeResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetActivityByTypeResponse")
    @Action(input = "http://soap.document.introsde/DB/getActivityByTypeRequest", output = "http://soap.document.introsde/DB/getActivityByTypeResponse")
    public List<Activity> getActivityByType(
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @param name
     * @return
     *     returns java.util.List<introsde.document.soap.Activity>
     */
    @WebMethod
    @WebResult(name = "activities", targetNamespace = "")
    @RequestWrapper(localName = "getActivityByName", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetActivityByName")
    @ResponseWrapper(localName = "getActivityByNameResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetActivityByNameResponse")
    @Action(input = "http://soap.document.introsde/DB/getActivityByNameRequest", output = "http://soap.document.introsde/DB/getActivityByNameResponse")
    public List<Activity> getActivityByName(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param calories
     * @return
     *     returns java.util.List<introsde.document.soap.Activity>
     */
    @WebMethod
    @WebResult(name = "activities", targetNamespace = "")
    @RequestWrapper(localName = "getActivityByCalories", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetActivityByCalories")
    @ResponseWrapper(localName = "getActivityByCaloriesResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetActivityByCaloriesResponse")
    @Action(input = "http://soap.document.introsde/DB/getActivityByCaloriesRequest", output = "http://soap.document.introsde/DB/getActivityByCaloriesResponse")
    public List<Activity> getActivityByCalories(
        @WebParam(name = "calories", targetNamespace = "")
        double calories);

    /**
     * 
     * @param activityIn
     * @return
     *     returns introsde.document.soap.Activity
     */
    @WebMethod
    @WebResult(name = "activity", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "createActivity", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.CreateActivity")
    @ResponseWrapper(localName = "createActivityResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.CreateActivityResponse")
    @Action(input = "http://soap.document.introsde/DB/createActivityRequest", output = "http://soap.document.introsde/DB/createActivityResponse")
    public Activity createActivity(
        @WebParam(name = "activityIn", targetNamespace = "")
        Activity activityIn);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.document.soap.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "getAllGoal", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetAllGoal")
    @ResponseWrapper(localName = "getAllGoalResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetAllGoalResponse")
    @Action(input = "http://soap.document.introsde/DB/getAllGoalRequest", output = "http://soap.document.introsde/DB/getAllGoalResponse")
    public List<Goal> getAllGoal();

    /**
     * 
     * @param idGoal
     * @return
     *     returns introsde.document.soap.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "getGoalById", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetGoalById")
    @ResponseWrapper(localName = "getGoalByIdResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetGoalByIdResponse")
    @Action(input = "http://soap.document.introsde/DB/getGoalByIdRequest", output = "http://soap.document.introsde/DB/getGoalByIdResponse")
    public Goal getGoalById(
        @WebParam(name = "idGoal", targetNamespace = "")
        Long idGoal);

    /**
     * 
     * @param type
     * @param userId
     * @return
     *     returns java.util.List<introsde.document.soap.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "getGoalByType", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetGoalByType")
    @ResponseWrapper(localName = "getGoalByTypeResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetGoalByTypeResponse")
    @Action(input = "http://soap.document.introsde/DB/getGoalByTypeRequest", output = "http://soap.document.introsde/DB/getGoalByTypeResponse")
    public List<Goal> getGoalByType(
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "userId", targetNamespace = "")
        long userId);

    /**
     * 
     * @param userId
     * @return
     *     returns java.util.List<introsde.document.soap.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "getGoalNotAchieved", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetGoalNotAchieved")
    @ResponseWrapper(localName = "getGoalNotAchievedResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetGoalNotAchievedResponse")
    @Action(input = "http://soap.document.introsde/DB/getGoalNotAchievedRequest", output = "http://soap.document.introsde/DB/getGoalNotAchievedResponse")
    public List<Goal> getGoalNotAchieved(
        @WebParam(name = "userId", targetNamespace = "")
        long userId);

    /**
     * 
     * @param userId
     * @return
     *     returns java.util.List<introsde.document.soap.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "getGoalAchieved", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetGoalAchieved")
    @ResponseWrapper(localName = "getGoalAchievedResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetGoalAchievedResponse")
    @Action(input = "http://soap.document.introsde/DB/getGoalAchievedRequest", output = "http://soap.document.introsde/DB/getGoalAchievedResponse")
    public List<Goal> getGoalAchieved(
        @WebParam(name = "userId", targetNamespace = "")
        long userId);

    /**
     * 
     * @param endAt
     * @return
     *     returns java.util.List<introsde.document.soap.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "getGoalEndAt", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetGoalEndAt")
    @ResponseWrapper(localName = "getGoalEndAtResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetGoalEndAtResponse")
    @Action(input = "http://soap.document.introsde/DB/getGoalEndAtRequest", output = "http://soap.document.introsde/DB/getGoalEndAtResponse")
    public List<Goal> getGoalEndAt(
        @WebParam(name = "endAt", targetNamespace = "")
        XMLGregorianCalendar endAt);

    /**
     * 
     * @param type
     * @return
     *     returns java.util.List<introsde.document.soap.Goal>
     */
    @WebMethod
    @WebResult(name = "goals", targetNamespace = "")
    @RequestWrapper(localName = "controlGoal", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.ControlGoal")
    @ResponseWrapper(localName = "controlGoalResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.ControlGoalResponse")
    @Action(input = "http://soap.document.introsde/DB/controlGoalRequest", output = "http://soap.document.introsde/DB/controlGoalResponse")
    public List<Goal> controlGoal(
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @param goalIn
     * @return
     *     returns introsde.document.soap.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "createGoal", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.CreateGoal")
    @ResponseWrapper(localName = "createGoalResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.CreateGoalResponse")
    @Action(input = "http://soap.document.introsde/DB/createGoalRequest", output = "http://soap.document.introsde/DB/createGoalResponse")
    public Goal createGoal(
        @WebParam(name = "goalIn", targetNamespace = "")
        Goal goalIn);

    /**
     * 
     * @param goalIn
     * @return
     *     returns introsde.document.soap.Goal
     */
    @WebMethod
    @WebResult(name = "goal", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "updateGoal", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.UpdateGoal")
    @ResponseWrapper(localName = "updateGoalResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.UpdateGoalResponse")
    @Action(input = "http://soap.document.introsde/DB/updateGoalRequest", output = "http://soap.document.introsde/DB/updateGoalResponse")
    public Goal updateGoal(
        @WebParam(name = "goalIn", targetNamespace = "")
        Goal goalIn);

    /**
     * 
     * @return
     *     returns java.util.List<introsde.document.soap.HealthMeasure>
     */
    @WebMethod
    @WebResult(name = "healthMeasures", targetNamespace = "")
    @RequestWrapper(localName = "getAllHealthMeasure", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetAllHealthMeasure")
    @ResponseWrapper(localName = "getAllHealthMeasureResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetAllHealthMeasureResponse")
    @Action(input = "http://soap.document.introsde/DB/getAllHealthMeasureRequest", output = "http://soap.document.introsde/DB/getAllHealthMeasureResponse")
    public List<HealthMeasure> getAllHealthMeasure();

    /**
     * 
     * @param idUser
     * @return
     *     returns java.util.List<introsde.document.soap.HealthMeasure>
     */
    @WebMethod
    @WebResult(name = "healthMeasures", targetNamespace = "")
    @RequestWrapper(localName = "getHealthMeasureByIdUser", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetHealthMeasureByIdUser")
    @ResponseWrapper(localName = "getHealthMeasureByIdUserResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetHealthMeasureByIdUserResponse")
    @Action(input = "http://soap.document.introsde/DB/getHealthMeasureByIdUserRequest", output = "http://soap.document.introsde/DB/getHealthMeasureByIdUserResponse")
    public List<HealthMeasure> getHealthMeasureByIdUser(
        @WebParam(name = "idUser", targetNamespace = "")
        Long idUser);

    /**
     * 
     * @param idUser
     * @param type
     * @return
     *     returns java.util.List<introsde.document.soap.HealthMeasure>
     */
    @WebMethod
    @WebResult(name = "healthMeasures", targetNamespace = "")
    @RequestWrapper(localName = "getHealthMeasureByIdUserType", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetHealthMeasureByIdUserType")
    @ResponseWrapper(localName = "getHealthMeasureByIdUserTypeResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.GetHealthMeasureByIdUserTypeResponse")
    @Action(input = "http://soap.document.introsde/DB/getHealthMeasureByIdUserTypeRequest", output = "http://soap.document.introsde/DB/getHealthMeasureByIdUserTypeResponse")
    public List<HealthMeasure> getHealthMeasureByIdUserType(
        @WebParam(name = "idUser", targetNamespace = "")
        Long idUser,
        @WebParam(name = "type", targetNamespace = "")
        String type);

    /**
     * 
     * @param healthMeasureIn
     * @return
     *     returns introsde.document.soap.HealthMeasure
     */
    @WebMethod
    @WebResult(name = "healthMeasure", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "createHealthMeasure", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.CreateHealthMeasure")
    @ResponseWrapper(localName = "createHealthMeasureResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.CreateHealthMeasureResponse")
    @Action(input = "http://soap.document.introsde/DB/createHealthMeasureRequest", output = "http://soap.document.introsde/DB/createHealthMeasureResponse")
    public HealthMeasure createHealthMeasure(
        @WebParam(name = "healthMeasureIn", targetNamespace = "")
        HealthMeasure healthMeasureIn);

    /**
     * 
     * @param healthMeasureIn
     * @return
     *     returns introsde.document.soap.HealthMeasure
     */
    @WebMethod
    @WebResult(name = "healthMeasure", targetNamespace = "http://soap.document.introsde/")
    @RequestWrapper(localName = "updateHealthMeasure", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.UpdateHealthMeasure")
    @ResponseWrapper(localName = "updateHealthMeasureResponse", targetNamespace = "http://soap.document.introsde/", className = "introsde.document.soap.UpdateHealthMeasureResponse")
    @Action(input = "http://soap.document.introsde/DB/updateHealthMeasureRequest", output = "http://soap.document.introsde/DB/updateHealthMeasureResponse")
    public HealthMeasure updateHealthMeasure(
        @WebParam(name = "healthMeasureIn", targetNamespace = "")
        HealthMeasure healthMeasureIn);

}
