
package introsde.document.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DBService", targetNamespace = "http://soap.document.introsde/", wsdlLocation = "http://infinite-savannah-53051.herokuapp.com/ws/db?wsdl")
public class DBService
    extends Service
{

    private final static URL DBSERVICE_WSDL_LOCATION;
    private final static WebServiceException DBSERVICE_EXCEPTION;
    private final static QName DBSERVICE_QNAME = new QName("http://soap.document.introsde/", "DBService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://infinite-savannah-53051.herokuapp.com/ws/db?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DBSERVICE_WSDL_LOCATION = url;
        DBSERVICE_EXCEPTION = e;
    }

    public DBService() {
        super(__getWsdlLocation(), DBSERVICE_QNAME);
    }

    public DBService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DBSERVICE_QNAME, features);
    }

    public DBService(URL wsdlLocation) {
        super(wsdlLocation, DBSERVICE_QNAME);
    }

    public DBService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DBSERVICE_QNAME, features);
    }

    public DBService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DBService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DB
     */
    @WebEndpoint(name = "DBImplPort")
    public DB getDBImplPort() {
        return super.getPort(new QName("http://soap.document.introsde/", "DBImplPort"), DB.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DB
     */
    @WebEndpoint(name = "DBImplPort")
    public DB getDBImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.document.introsde/", "DBImplPort"), DB.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DBSERVICE_EXCEPTION!= null) {
            throw DBSERVICE_EXCEPTION;
        }
        return DBSERVICE_WSDL_LOCATION;
    }

}
