
package introsde.document.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DB", targetNamespace = "http://ws.document.introsde/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DB {


    /**
     * 
     * @param password
     * @param userName
     * @return
     *     returns introsde.document.ws.User
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://ws.document.introsde/")
    @RequestWrapper(localName = "loginUser", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.LoginUser")
    @ResponseWrapper(localName = "loginUserResponse", targetNamespace = "http://ws.document.introsde/", className = "introsde.document.ws.LoginUserResponse")
    @Action(input = "http://ws.document.introsde/DB/loginUserRequest", output = "http://ws.document.introsde/DB/loginUserResponse")
    public User loginUser(
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
